### ISSUE TITLE
Remove button from courses page

### ISSUE THREAD

**Issue by Szakalka1234** [rafaelcichocki/99grit.com#38]
https://www.99grit.com/courses - we would like to remove the button (however, it's confusing)
<img width="613" alt="Zrzut ekranu 2021-12-31 o 10 59 28" src="https://user-images.githubusercontent.com/94043959/147816854-01a88561-e05f-4ddc-a11e-19d4b55a7124.png">

**Comment by rafaelcichocki** [comment]
The cta and ctaLink in the CMS just need to be set to empty-strings.
I made the change.
