### ISSUE TITLE
readability - if this sounds like you

### ISSUE THREAD

**Issue by Szakalka1234** [rafaelcichocki/99grit.com#42]
Could you calculate the costs this change? This section is hard to read, so we change a design again. 
This is not a top priority - we can change it later.

![If this sounds like you - desktop](https://user-images.githubusercontent.com/94043959/147887124-ef49c648-7b7c-4bd5-8b51-2175b4456b28.jpg)
![If this sounds like you - mobile](https://user-images.githubusercontent.com/94043959/147887130-daade44e-8047-405a-855e-763f2f847d44.jpg)
![Sound like you - desktop](https://user-images.githubusercontent.com/94043959/147887131-accf1490-a4d8-4fb0-b47a-744ce12b5700.jpg)
![Sound like you - mobile](https://user-images.githubusercontent.com/94043959/147887132-797bdcc9-45ec-4e5d-b371-a76d2d1e27e1.jpg)

**Comment by rafaelcichocki** [comment]
* left-align the text instead of center
* + refactoring for reuse of same style component (1sp)

**Comment by Szakalka1234** [comment]
Hey There,

The copy looks different than in the design. It's uppercase, and should be lowercase.

**Comment by rafaelcichocki** [comment]
You're right. I'll fix it.
