### ISSUE TITLE
Bug in CMS

### ISSUE THREAD

**Issue by Szakalka1234** [rafaelcichocki/99grit.com#61]
Hey, there is a problem with courses page. When I try to change something message appears:

<img width="876" alt="Zrzut ekranu 2022-01-6 o 11 11 04" src="https://user-images.githubusercontent.com/94043959/148366691-874b4ae8-4523-4ab9-87d0-b1bd784e5067.png">
<img width="609" alt="Zrzut ekranu 2022-01-6 o 11 08 16" src="https://user-images.githubusercontent.com/94043959/148366734-1a8fd3b5-18c7-41fe-bbaf-2e0b825aaabf.png">

**Comment by rafaelcichocki** [comment]
Ok, yep - I need to set the CTA as not-required. Thx.
